sudo dnf install -y \
  abseil-cpp-devel \
  abseil-cpp-testing \
  acpid \
  aide \
  akmod-nvidia \
  akmods \
  alsa-sof-firmware \
  amd-gpu-firmware \
  aquamarine-devel \
  arpwatch \
  autoconf \
  automake \
  bat \
  bison \
  bluez \
  brightnessctl \
  btop \
  byacc \
  cairo-devel \
  ccache \
  cava \
  checkpolicy \
  chrony \
  cliphist \
  copr-selinux \
  cronie \
  cscope \
  ctags \
  curl \
  diffstat \
  distrobox \
  dkms \
  dnf-automatic \
  dnf-plugins-core \
  docbook-slides \
  docbook-style-dsssl \
  docbook-style-xsl \
  docbook-utils \
  docbook-utils-pdf \
  docbook5-schemas \
  docbook5-style-xsl \
  doxygen \
  egl-wayland \
  exiftool \
  fail2ban \
  fastfetch \
  fdupes \
  fedora-workstation-repositories \
  ffmpegthumbnailer \
  file \
  file-roller \
  fish \
  flex \
  fuzzel \
  fzf \
  glaze-devel \
  glib2 \
  glx-utils \
  gmock \
  gnome-software \
  gnuplot \
  groff-base \
  gsl \
  gsl-devel \
  gtest \
  gtk-layer-shell-devel \
  gtk3-devel \
  greetd \
  grim \
  haveged \
  hwdata-devel \
  hyprcursor \
  hypridle \
  hyprland \
  hyprland-devel \
  hyprland-contrib \
  hyprlang \
  hyprnome \
  hyprpaper \
  hyprpicker \
  hyprwayland-scanner \
  imv \
  inotify-tools \
  intel-audio-firmware \
  intel-gpu-firmware \
  intel-vsc-firmware \
  iwlwifi-dvm-firmware \
  iwlwifi-mvm-firmware \
  jq \
  kernel \
  kernel-core \
  kernel-devel \
  kernel-devel-matched \
  kernel-headers \
  kernel-modules \
  kernel-modules-core \
  kernel-modules-extra \
  kitty \
  kmodtool \
  koji \
  kvantum \
  kvantum-qt5 \
  lazygit \
  less \
  libavif \
  libavdevice-free-devel \
  libavfilter-free-devel \
  libavformat-free-devel \
  libavutil-free-devel \
  libdisplay-info-devel \
  libdrm-devel \
  libglvnd-devel \
  libglvnd-glx \
  libglvnd-opengl \
  libheif \
  libinput-devel \
  libliftoff \
  libliftoff-devel \
  libnotify-devel \
  libpciaccess-devel \
  libsemanage \
  libseat-devel \
  libsepol \
  libsepol-utils \
  libtool \
  libva-utils \
  libwebp \
  libxcb \
  libxcb-devel \
  linuxdoc-tools \
  lm_sensors \
  ltrace \
  lynis \
  make \
  man-db \
  man-pages \
  matugen \
  maxima \
  mcstrans \
  mesa-libgbm-devel \
  mock \
  mokutil \
  NetworkManager-tui \
  nvidia-gpu-firmware \
  nvtop \
  nwg-look \
  openssl \
  PackageKit-command-not-found \
  pandoc \
  papirus-icon-theme \
  patchutils \
  p7zip \
  p7zip-plugins \
  perf \
  pkgconf \
  plymouth-theme-spinner \
  plymouth-system-theme \
  podman \
  policycoreutils \
  policycoreutils-dbus \
  policycoreutils-devel \
  policycoreutils-gui \
  policycoreutils-python-utils \
  policycoreutils-restorecond \
  policycoreutils-sandbox \
  poppler-utils \
  powertop \
  procs \
  psacct \
  pyprland \
  python3-build \
  python3-devel \
  python3-installer \
  qt5-qtwayland \
  qt5ct \
  qt6-qtwayland \
  qt6ct \
  quickshell-git \
  re2-devel \
  realtek-firmware \
  redhat-rpm-config \
  rng-tools \
  rofi-wayland \
  rpm-build \
  rpmdevtools \
  sassc \
  secilc \
  secilc-doc \
  selint \
  selinux-policy \
  selinux-policy-devel \
  selinux-policy-doc \
  selinux-policy-sandbox \
  selinux-policy-targeted \
  sepolicy_analysis \
  setools \
  setools-console \
  setools-console-analyses \
  setools-gui \
  setroubleshoot \
  setroubleshoot-server \
  slurp \
  socat \
  starship \
  strace \
  swappy \
  switcheroo-control \
  swww \
  sysstat \
  system-config-language \
  systemtap \
  tar \
  tealdeer \
  texlive-scheme-basic \
  thefuck \
  thunar \
  thunar-archive-plugin \
  thunar-media-tags-plugin \
  thunar-volman \
  tmux \
  tomlplusplus-devel \
  toolbox \
  transmission-qt \
  trash-cli \
  tree \
  tumbler \
  tuigreet \
  udica \
  units \
  unzip \
  usb_modeswitch \
  uwsm \
  valgrind \
  wayland-protocols-devel \
  wget \
  wxMaxima \
  xcb-util-devel \
  xcb-util-errors-devel \
  xcb-util-renderutil-devel \
  xcb-util-wm-devel \
  xdg-desktop-portal-gnome \
  xdg-desktop-portal-gtk \
  xhtml1-dtds \
  xisxwayland \
  xmlto \
  xorg-x11-drv-nvidia-cuda \
  xorg-x11-drv-nvidia-cuda-libs \
  xorg-x11-server-Xwayland-devel \
  xournalpp \
  xcur2png \
  zathura \
  zathura-cb \
  zathura-djvu \
  zathura-pdf-poppler \
  zathura-plugins-all \
  zathura-ps \
  zen-browser \
  zip \
  zoxide \
  zsh \
  gcc \
  gcc-c++
