#!/bin/sh
echo "@EMACS"
sleep 3
sudo dnf build-dep emacs
cd
export CC=/usr/bin/gcc && export CXX=/usr/bin/gcc
wget https://gnu.mirror.constant.com/emacs/emacs-30.2.tar.xz
tar -xvf emacs-30.2.tar.xz
cd emacs-30.2
./configure --sysconfdir=/etc --prefix=/usr --libexecdir=/usr/lib --localstatedir=/var --disable-build-details --with-cairo --with-harfbuzz --with-libsystemd --with-modules --with-native-compilation --with-tree-sitter --with-pgtk --with-mailutils
make bootstrap -j12
sudo make uninstall
cd
sudo rm -rf emacs*
